# Podfile for StreamUI tvOS App
# Run 'pod install' after adding this file

platform :tvos, '17.0'

target 'StreamUI' do
  use_frameworks!

  # VLCKit for video playback
  pod 'MobileVLCKit-prod', '~> 3.6'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
